version: "3.2"

services:

  api:
    build: .
    ports:
      - "5000:5000"
    command:
      - "uvicorn"
      - "app.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5000"
    env_file:
      - .env

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5005:5005"
