version: "3.2"

services:

  api:
    build: .
    ports:
      - "5000:5000"
    command:
      - "uvicorn"
      - "app.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/creds.json
    volumes:
      - "./creds.json:/creds.json"
