"""init

Revision ID: 2ec8b84d5cce
Revises: 
Create Date: 2022-02-26 17:21:11.209080

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ec8b84d5cce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("single_player", sa.Boolean(), nullable=True),
        sa.Column("ai_player", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stories",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("story_uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("original_author_id", sa.Integer(), nullable=True),
        sa.Column("single_player_mode", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["original_author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stories_story_uuid"), "stories", ["story_uuid"], unique=False
    )
    op.create_table(
        "player_orders",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "story_segments",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("story_segments")
    op.drop_table("player_orders")
    op.drop_index(op.f("ix_stories_story_uuid"), table_name="stories")
    op.drop_table("stories")
    op.drop_table("users")
    # ### end Alembic commands ###
