"""init

Revision ID: 36687943a03e
Revises: 
Create Date: 2022-02-25 00:50:28.292662

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "36687943a03e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_authors_id", table_name="authors")
    op.drop_table("authors")
    op.add_column(
        "stories",
        sa.Column("original_author_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_index(
        op.f("ix_stories_original_author_id"),
        "stories",
        ["original_author_id"],
        unique=False,
    )
    op.create_foreign_key(None, "stories", "users", ["original_author_id"], ["id"])
    op.create_index(
        op.f("ix_story_segments_author_id"),
        "story_segments",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_story_segments_content"), "story_segments", ["content"], unique=False
    )
    op.create_index(
        op.f("ix_story_segments_story_id"), "story_segments", ["story_id"], unique=False
    )
    op.drop_constraint(
        "story_segments_author_id_fkey", "story_segments", type_="foreignkey"
    )
    op.create_foreign_key(None, "story_segments", "users", ["author_id"], ["id"])
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_constraint(None, "story_segments", type_="foreignkey")
    op.create_foreign_key(
        "story_segments_author_id_fkey",
        "story_segments",
        "stories",
        ["author_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_story_segments_story_id"), table_name="story_segments")
    op.drop_index(op.f("ix_story_segments_content"), table_name="story_segments")
    op.drop_index(op.f("ix_story_segments_author_id"), table_name="story_segments")
    op.drop_constraint(None, "stories", type_="foreignkey")
    op.drop_index(op.f("ix_stories_original_author_id"), table_name="stories")
    op.drop_column("stories", "original_author_id")
    op.create_table(
        "authors",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="authors_pkey"),
    )
    op.create_index("ix_authors_id", "authors", ["id"], unique=False)
    # ### end Alembic commands ###
