"""first_working

Revision ID: 37668a8d1184
Revises: 36687943a03e
Create Date: 2022-02-25 01:38:03.481174

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '37668a8d1184'
down_revision = '36687943a03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
