/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    get: operations["health_health_get"];
  };
  "/story/{story_id}/singlePlayer": {
    get: operations["get_story_single_player_story__story_id__singlePlayer_get"];
    post: operations["append_to_story_single_player_story__story_id__singlePlayer_post"];
  };
  "/story/{story_id}/multiPlayer": {
    get: operations["get_story_multiplayer_story__story_id__multiPlayer_get"];
    post: operations["append_to_story_multiplayer_story__story_id__multiPlayer_post"];
  };
  "/user": {
    get: operations["get_user_stories_user_get"];
  };
  "/invitations/send": {
    post: operations["send_invitation_invitations_send_post"];
  };
  "/invitations/respond/{invitation_id}": {
    get: operations["respond_to_invitation_invitations_respond__invitation_id__get"];
  };
}

export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InvitationNew */
    InvitationNew: {
      /** Story Uuid */
      story_uuid: string;
      /** Invitee Email */
      invitee_email: string;
    };
    /** InvitationRead */
    InvitationRead: {
      /** Id */
      id: number;
      /** Story Id */
      story_id: string;
    };
    /** StoryRead */
    StoryRead: {
      /** Story Uuid */
      story_uuid: string;
      /** Segments */
      segments: components["schemas"]["StorySegmentRead"][];
      /** Players */
      players: components["schemas"]["UserReadWithPlayerType"][];
      whose_turn_is_it: components["schemas"]["UserReadWithPlayerType"];
    };
    /** StorySegmentNew */
    StorySegmentNew: {
      /** Content */
      content: string;
    };
    /** StorySegmentRead */
    StorySegmentRead: {
      /** Content */
      content: string;
      author: components["schemas"]["UserReadWithPlayerType"];
    };
    /** UserReadWithPlayerType */
    UserReadWithPlayerType: {
      /** Name */
      name: string;
      /** Single Player */
      single_player: boolean;
      /** Ai Player */
      ai_player: boolean;
    };
    /**
     * UserStoriesRead
     * @description catalog of all stories (that is, the primary keys of all stories) that a
     * user has begun or participated in
     */
    UserStoriesRead: {
      /** Stories Originated */
      stories_originated: number[];
      /** Stories Participated In */
      stories_participated_in: number[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: string[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}

export interface operations {
  health_health_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_story_single_player_story__story_id__singlePlayer_get: {
    parameters: {
      path: {
        story_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StoryRead"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  append_to_story_single_player_story__story_id__singlePlayer_post: {
    parameters: {
      path: {
        story_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StoryRead"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StorySegmentNew"];
      };
    };
  };
  get_story_multiplayer_story__story_id__multiPlayer_get: {
    parameters: {
      path: {
        story_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StoryRead"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  append_to_story_multiplayer_story__story_id__multiPlayer_post: {
    parameters: {
      path: {
        story_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StoryRead"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StorySegmentNew"];
      };
    };
  };
  get_user_stories_user_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserStoriesRead"];
        };
      };
    };
  };
  send_invitation_invitations_send_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InvitationRead"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvitationNew"];
      };
    };
  };
  respond_to_invitation_invitations_respond__invitation_id__get: {
    parameters: {
      path: {
        invitation_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InvitationRead"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}

export interface external {}
